config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'

  post 'books' => 'books#create'

  get 'books' => 'books#index'

  get 'books/:id' => 'books#show', as: 'book'

  get 'books/:id/edit' => 'books#edit', as: 'edit_book'

  patch 'books/:id' => 'books#update', as: 'update_book'

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates :title,presence: true

	validates :body,presence: true
end

app/models/book.rb
class Book < ApplicationRecord

	validates :title,presence: true,length: { maximum: 50 }
	validates :body,presence: true,length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def new
	 @blog = Blog.new
	 @blogs = Blog.all
	end

	def create
		@blog = Blog.new(blog_params)
		if @blog.save
			flash[:notice] = " Book was successfully created."
			redirect_to blog_path(@blog.id)
		else
			@blogs = Blog.all
			render :new
		end
	end
	def index
		@blogs = Blog.all
	end

	def show
		@blog = Blog.find(params[:id])
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		blog = Blog.find(params[:id])
		blog.update(blog_params)
		redirect_to blog_path(blog.id)

	end

	def destroy
		blog = Blog.find(params[:id])
		blog.destroy
		redirect_to blogs_path

	end

	private

	def blog_params
        params.require(:blog).permit(:title, :body)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  	@book = Book.new
	@books = Book.all
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			flash[:notice] = " Book was successfully created."
			redirect_to book_path(@book.id)
		else
			@books = Book.all
			render :new
		end
	end
	def index
		@book = Book.new
		@books = Book.all
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		book = Book.find(params[:id])
		book.update(book_params)
		flash[:notice] = " Book was successfully created."
		redirect_to book_path(book.id)

	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path

	end

	private

	def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@blog, url:"/blogs/#{@blog.id}") do |f| %>

    <h4>Title</h4>

    <%= f.text_field :title %>

    <h4>Body</h4>

    <%= f.text_area :body %>

    <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "show", blog_path(@blog.id)%>
<%= link_to "back", blogs_new_path%>

app/views/blogs/new.html.erb
<h1>Books</h1>

 <table border="0">


 	<tr>
 		<th>タイトル</th><th>Body</th>
 	</tr>
<tr>
 <% @blogs.each do |blog| %>
    <td><%=blog.title %></td>
    <td><%=blog.body %></td>
    <td><%=link_to "edit",edit_blog_path(blog.id)%></td>
    <td><%=link_to "show",blog_path(blog.id)%></td>
    <td><%=link_to "destroy",destroy_blog_path(blog.id),
    method: :delete, "date-confirm" => "本当に削除しますか？" %></td>
 </tr>

<% end %>
</table>

<h1>New Book</h1>
<% if @blog.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- form_for部分 -->
<%= form_for(@blog) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>



<% end %>

app/views/blogs/show.html.erb
<% if flash[:notice] %>
<div class= "flash">
	<%= flash[:notice] %>
</div>
<% end %>



<h2>Title</h2>

<p><%= @blog.title %></p>

<h2>Body</h2>

<p><%= @blog.body %></p>



<%= link_to "edit", edit_blog_path(@blog.id) %>

<%= link_to "back", :back %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>

    <h4>Title</h4>

    <%= f.text_field :title %>

    <h4>Body</h4>

    <%= f.text_area :body %>

    <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "show", book_path(@book.id)%>
<%= link_to "back", books_new_path%>

app/views/books/index.html.erb
<h1>Books</h1>

 <table border="0">


 	<tr>
 		<th>タイトル</th><th>Body</th>
 	</tr>
<tr>
 <% @books.each do |book| %>
    <td><%=book.title %></td>
    <td><%=book.body %></td>
    <td><%=link_to "edit",edit_book_path(book.id)%></td>
    <td><%=link_to "show",book_path(book.id)%></td>
    <td><%=link_to "destroy",destroy_book_path(book.id),
    method: :delete, data:{confirm:"本当に削除しますか？"} %></td>
 </tr>

<% end %>
</table>

<h1>New Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- form_for部分 -->
<%= form_for(@book) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>


<% end %>

app/views/books/new.html.erb
<h1>Books</h1>

 <table border="0">


 	<tr>
 		<th>タイトル</th><th>Body</th>
 	</tr>
<tr>
 <% @books.each do |book| %>
    <td><%=book.title %></td>
    <td><%=book.body %></td>
    <td><%=link_to "edit",edit_book_path(book.id)%></td>
    <td><%=link_to "show",book_path(book.id)%></td>
    <td><%=link_to "destroy",destroy_book_path(book.id),
    method: :delete, data:{confirm:"本当に削除しますか？"} %></td>
 </tr>

<% end %>
</table>

<h1>New Book</h1>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- form_for部分 -->
<%= form_for(@book) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>


<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
<div class= "flash">
	<%= flash[:notice] %>
</div>
<% end %>



<h2>Title</h2>

<p><%= @book.title %></p>

<h2>Body</h2>

<p><%= @book.body %></p>

<%= link_to "edit", edit_book_path(@book.id) %>

<%= link_to "back", books_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/top.html.erb
<h1>ようこそ Bookersへ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
	印象を共有し交換することができます</p>
<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>